import React from 'react';

export default function IndexSectionCtaWhitePattern12() {
    return (
        <React.Fragment>
            <>
                <section className="py-24 bg-white overflow-hidden" style={{backgroundImage: 'url("flex-ui-assets/elements/pattern-white.svg")', backgroundPosition: 'center'}}>  <div className="container px-4 mx-auto">    <div className="flex flex-wrap -mx-4">      <div className="w-full md:w-1/2 px-4 mb-20 lg:mb-0">        <div className="max-w-md mx-auto">          <h2 className="mb-8 text-4xl md:text-5xl font-heading font-bold text-coolGray-900 md:leading-15">Afla ce avantaje iti aduce agriK prin:</h2>          <ul className="mb-8">            <li className="flex items-center mb-4">              <img className="mr-3" src="flex-ui-assets/elements/cta/checkbox-green.svg" alt />              <span className="text-lg md:text-xl font-heading text-coolGray-500">Calendar agricol al culturilor</span>          </li>            <li className="flex items-center mb-4">              <img className="mr-3" src="flex-ui-assets/elements/cta/checkbox-green.svg" alt />              <span className="text-lg md:text-xl font-heading text-coolGray-500">Evidența </span>          </li>            <li className="flex items-center mb-4">              <img className="mr-3" src="flex-ui-assets/elements/cta/checkbox-green.svg" alt />              <span className="text-lg md:text-xl font-heading text-coolGray-500">Identificare simplă a dăunătorilor</span>          </li>            <li className="flex items-center mb-4">              <img className="mr-3" src="flex-ui-assets/elements/cta/checkbox-green.svg" alt />              <span className="text-lg md:text-xl font-heading text-coolGray-500">Integrarea stației meteo</span>          </li>            <li className="flex items-center">              <img className="mr-3" src="flex-ui-assets/elements/cta/checkbox-green.svg" alt />              <span className="text-lg md:text-xl font-heading text-coolGray-500">Recomandări bazate  pe cercetare științifică cu ajutorul AI</span>          </li>        </ul>          <div className="flex flex-wrap items-center"><a className="inline-flex items-center justify-center px-7 py-3 h-14 w-full md:w-auto text-lg leading-7 text-green-50 bg-green-500 hover:bg-green-600 font-medium focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 border border-transparent rounded-md shadow-sm" href="#">Completeza Chestionarul</a></div>      </div>    </div>      <div className="w-full md:w-1/2 px-4">        <div className="relative max-w-max mx-auto">          <img className="absolute top-0 right-0 -mt-6 lg:-mt-12 -mr-6 lg:-mr-12 w-20 lg:w-auto z-10" src="flex-ui-assets/elements/circle3-yellow.svg" alt />          <img className="absolute bottom-0 left-0 -mb-6 lg:-mb-10-ml-6 lg:-ml-12 w-20 lg:w-auto" src="flex-ui-assets/elements/dots3-blue.svg" alt />          <img className="relative" src="flex-ui-assets/elements/cta/photo-laptop-ph.png" alt />      </div>    </div>  </div></div></section>


            </>
        </React.Fragment>
    );
}

